package com.daemonz.common.theme.dark

import androidx.compose.ui.graphics.Color
import com.daemonz.common.theme.FidoColorScheme

fun fidoDarkColorScheme(
    onBackground: Color = ColorDarkTokens.Secondaryest,
    Primary: Color = ColorDarkTokens.Primary,
    Primaryer : Color = ColorDarkTokens.Primaryer,
    Primaryest : Color = ColorDarkTokens.Primaryest,
    Secondary : Color = ColorDarkTokens.Secondary,
    Secondaryer : Color = ColorDarkTokens.Secondaryer,
    Secondaryest : Color = ColorDarkTokens.Secondaryest,
    Neutral_TextColors_HighEmp : Color = ColorDarkTokens.Neutral_TextColors_HighEmp,
    Neutral_TextColors_MidEmp : Color = ColorDarkTokens.Neutral_TextColors_MidEmp,
    Neutral_TextColors_LowEmp : Color = ColorDarkTokens.Neutral_TextColors_LowEmp,
    Neutral_TextColorsDisabled : Color = ColorDarkTokens.Neutral_TextColorsDisabled,
    Neutral_TextColorsGreyPurpleHighEmp : Color = ColorDarkTokens.Neutral_TextColorsGreyPurpleHighEmp,
    Neutral_TextColorsGreyPurpleLowEmp : Color = ColorDarkTokens.Neutral_TextColorsGreyPurpleLowEmp,
    Neutral_TextColorsGreyPurpleBlack : Color = ColorDarkTokens.Neutral_TextColorsGreyPurpleBlack,
    StatusColorError : Color = ColorDarkTokens.StatusColorError,
    StatusColorSuccess : Color = ColorDarkTokens.StatusColorSuccess,
    StatusColorWarning : Color = ColorDarkTokens.StatusColorWarning,
    StatusColorInfo : Color = ColorDarkTokens.StatusColorInfo,
    StatusColorAlert : Color = ColorDarkTokens.StatusColorAlert,
    Gradient1_start : Color = ColorDarkTokens.Gradient1_start,
    Gradient1_center : Color = ColorDarkTokens.Gradient1_center,
    Gradient1_end : Color = ColorDarkTokens.Gradient1_end,
    Gradient2_start : Color = ColorDarkTokens.Gradient2_start,
    Gradient2_end : Color = ColorDarkTokens.Gradient2_end,
): FidoColorScheme = FidoColorScheme(
    onBackground = onBackground,
    Primary = Primary,
    Primaryer = Primaryer,
    Primaryest = Primaryest,
    Secondary = Secondary,
    Secondaryer = Secondaryer,
    Secondaryest = Secondaryest,
    Neutral_TextColors_HighEmp = Neutral_TextColors_HighEmp,
    Neutral_TextColors_MidEmp = Neutral_TextColors_MidEmp,
    Neutral_TextColors_LowEmp = Neutral_TextColors_LowEmp,
    Neutral_TextColorsDisabled = Neutral_TextColorsDisabled,
    Neutral_TextColorsGreyPurpleHighEmp = Neutral_TextColorsGreyPurpleHighEmp,
    Neutral_TextColorsGreyPurpleLowEmp = Neutral_TextColorsGreyPurpleLowEmp,
    Neutral_TextColorsGreyPurpleBlack = Neutral_TextColorsGreyPurpleBlack,
    StatusColorError = StatusColorError,
    StatusColorSuccess = StatusColorSuccess,
    StatusColorWarning = StatusColorWarning,
    StatusColorInfo = StatusColorInfo,
    StatusColorAlert = StatusColorAlert,
    Gradient1_start = Gradient1_start,
    Gradient1_center = Gradient1_center,
    Gradient1_end = Gradient1_end,
    Gradient2_start = Gradient2_start,
    Gradient2_end = Gradient2_end,
    isLight = false,
)

